image: maven:3.5.0-jdk-8

 
stages:
 - build
 - test 
 
benchmark_build:
  stage: build
  only: 
  - master
  script:
    - mvn clean compile -DskipTests  assembly:single package

benchmark_tests:
  stage: test
  script:
    - mvn test
