image: maven:3.5.0-jdk-8

variables:
DOCKER_HOST: tcp://docker:2375/
 
stages:
 - build
 
benchmark_build:
  stage: build
  only: 
  - master
  script:
    - mvn clean compile assembly:single package
    - mvn docker:build
