version: '3'


services:

  reference-postgres-db:
    image: postgres:10.1
    ports:
     - "5431:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=mydb
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    healthcheck:
        test: ["CMD", "curl", "-f", "http://10.5.0.6:5432"]
        interval: 30s
        timeout: 10s
        retries: 5

  jm-app:
    image: jdbc-benchmark
    ports:
    - "8080:8080"
    depends_on:
      - reference-postgres-db
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5


networks:
    vpcbr:
        driver: bridge
        ipam:
          config:
            - subnet: 10.5.0.0/16
